[package]
name = "AQRR"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = { version = "0.11", default-features = false }
image = "0.23.14"

